# This is a basic workflow to help you get started with Actions

name: fetchLatestData

# Controls when the workflow will run
on:
  # Triggers the workflow every 3h
  schedule:
    - cron: '0 */3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Starting script fetchLatestData

      # Set up python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      # Set up python packages
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # execute python script fetchLatestSHP.py
      - name: execute python script
        env:
          KAC_USERNAME: ${{ secrets.KAC_USERNAME }}
          KAC_PASSWORD: ${{ secrets.KAC_PASSWORD }}
        run: python fetchLatestSHP.py
        
      # execute python script fetchLatestNC.py
      - name: execute python script
        env:
          KAC_USERNAME: ${{ secrets.KAC_USERNAME }}
          KAC_PASSWORD: ${{ secrets.KAC_PASSWORD }}
        run: python fetchLatestNC.py
      
      # commit files
      - name: commit files
        run: |
          git config --global http.version HTTP/1.1
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      # push changes
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
