# This is a basic workflow to help you get started with Actions

name: generateCsvLosses_15as

# Controls when the workflow will run
on:
  # Runs the workflow every 15 minutes
  # schedule:
    # - cron: '0 1-23 * * *'  # Runs at the top of every hour between 01:00 AM and 11:00 PM
    # - cron: '*/30 1-23 * * *'  # Runs every 30 minutes between 01:00 AM and 11:30 PM
    # - cron: '*/15 * * * *'# Controls when the workflow will run
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Starting script generateCsvLosses_15as

      # Set up python
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      # Set up python packages
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
        
      - name: execute python script generateCsvLosses_15as.py
        id: generate_csv_loss
        env:
          KAC_USERNAME: ${{ secrets.KAC_USERNAME }}
          KAC_PASSWORD: ${{ secrets.KAC_PASSWORD }}
        run: |
          output=$(python scripts/generateCsvLosses_15as.py)
          echo "$output"
          # Capture the values from the script's output
          files_to_process=$(echo "$output" | grep -oP '(?<=files_to_process=)\d+')
          files_processed=$(echo "$output" | grep -oP '(?<=files_processed=)\d+')
          echo "files_to_process=$files_to_process"
          echo "files_processed=$files_processed"
          echo "files_to_process=$files_to_process" >> $GITHUB_ENV
          echo "files_processed=$files_processed" >> $GITHUB_ENV
        
 # list files in mpres_data directory
      - name: List files in mpres_data directory
        run: ls -l mpres_data

      # list files in tc_realtime directory
      - name: List files in tc_realtime directory
        run: ls -l tc_realtime
        
      # execute python script createIndex.py
      - name: execute python script createIndex.py
        run: python scripts/createIndex.py
        
      # execute python script latestStorms.py
      - name: execute python script latestStorms.py
        run: python scripts/latestStorms.py

      # execute python script latestStorms_15as.py
      - name: execute python script latestStorms_15as.py
        run: python scripts/latestStorms_15as.py
        
      # execute python script pastStorms.py
      - name: execute python script pastStorms.py
        run: python scripts/pastStorms.py
        
      # execute python script getHistory.py
      - name: execute python script getHistory.py
        run: python scripts/getHistory.py
      
      # Show git log
      - name: show git log
        run: git log --oneline

      # Show git diff
      - name: show git diff
        run: git diff

      - name: commit files
        run: |
          git config --global http.version HTTP/1.1
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Add all files (new, modified, deleted)
          git add -A

          # Check if there are staged changes (committed vs. staged differences)
          if ! git diff --cached --quiet; then
            git commit -m "Generated 15as csv ($files_processed/$files_to_process files processed)"
          else
            echo "No changes to commit"
          fi
          
      # push changes
      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
